### PR TITLE
fix(cov):  hitting mocha timeout creates wrong cov

### LINKED ISSUE #613: feat: enable code coverage
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature Request

I need to enable coverage for the fortran-lang organisation and then add the node modules and action workflow that generates it and uploads it to coverage.io

### PR DESCRIPTION
**Pull request by gnikit**
Hitting the timeout in mocha unittesting leads to `c8`
creating erroneous coverage reports

Fixes #613

### CODE REVIEW

**Comment by gnikit** [comment]
@fortran-lang/admins I have send an access request to enable codecov, do you think we can give it a shot.

**Comment by awvwgk** [comment]
codecov is enabled in Fortran-lang already, I added this repository to the list of repos it is available on.

**Comment by gnikit** [comment]
> codecov is enabled in Fortran-lang already, I added this repository to the list of repos it is available on.

Cheers @awvwgk

**Comment by awvwgk** [comment]
The request is for private repo access, do we need this for @fortran-lang?

**Comment by gnikit** [comment]
> The request is for private repo access, do we need this for @fortran-lang?

nope, I think that was a mistake from my end.

**Comment by gnikit** [comment]
@awvwgk  Can you see vscode-fortran-support on your `codecov` list of repos? I can't seen fortran-lang there

image

I think the request was for private repos + modifying public repos which I guess includes creating and uploading cov stats

**Comment by awvwgk** [comment]
I think codecov is safe to have installed by default for the whole organization rather than only a dedicated repo list. Also approved the request for additional permissions (we don't have any private repos in the org anyway).

**Pull request merged**
